### PR TITLE
HTC-793: display business logos on listing cards

### PR DESCRIPTION
**Pull request by rachellegelden**
# [HTC-793](https://github.com/rachellegelden/Home-Together-Canada/issues/793)

## Summary
Business logos will now be displayed on the cards

## Relevant Motivation & Context
The HTC logo won't be displayed anymore

## Testing Instructions
Look at some listings for businesses that do and don't have logos

## Developer checklist prior to opening this pull request:

- [x] PR merges to the applicable branch (develop or feature branch)
- [x] Commits adhere to GitHub compliance (Issue #)
- [x] Comments for non-trivial changes
- [x] No build or runtime warnings or errors introduced
- [ ] If CSS changes were introduced, change viewed in Chrome, Firefox and IE
- [ ] Unit test coverage for features
- [ ] Unit tests pass
- [ ] Automation tests pass 

## Reviewer
- [ ] Checkout and launch this branch locally
- [ ] Review code structure
- [ ] Review test coverage
- [ ] If CSS changes were introduced, change viewed were viewed in Chrome, Firefox and IE

### CODE REVIEW

**Review by Lightbrite88 — COMMENTED** [review]
I am not currently seeing the logos. I will test with different images after client meeting, but currently this isn't working on my end.

**Review by Parsa-Rajabi — CHANGES_REQUESTED** [review]
Images are not being displayed on listing cards on admin > pending listings 

image

is it possible to display the home together logo in case the business do not have a logo? 
image

**Comment by Lightbrite88** [comment]
@rachellegelden I can confirm that this is what I was seeing as well.

**Review by Lightbrite88 — CHANGES_REQUESTED** [review]
This was what I am seeing - this was my listing that had a logo image added
image

**Review by Lightbrite88 — APPROVED** [review]
Works great now for me

**Review by Parsa-Rajabi — APPROVED** [review]
LGTM

**Pull request merged**
